server:
  port: 9000

spring:
  application:
    name: GatewayMS

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"

      routes:
        - id: UserMS
          uri: http://localhost:8080
          predicates:
            - Path=/user/**
          filters:
            - name: TokenFilter
